### ISSUE TITLE
servo360 punch list

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/Simple-Libraries#107]
- [ ] [abdrive360, servo360 - Instructions for setup and testing](https://github.com/parallaxinc/Simple-Libraries/issues/106)
- [ ] [servo360 - Make sans feedback mode work enhancement](https://github.com/parallaxinc/Simple-Libraries/issues/104)
- [ ] [servo360 - add code comments Component-Docs](https://github.com/parallaxinc/Simple-Libraries/issues/99)
- [ ] [servo360 - add code comments](https://github.com/parallaxinc/Simple-Libraries/issues/99) 
- [ ] [servo360 - add Doxygen comments & generate docs](https://github.com/parallaxinc/Simple-Libraries/issues/100)  
- [ ] [servo360 - fix servo360_goto so that it doesn't get confused by a new target angle](https://github.com/parallaxinc/Simple-Libraries/issues/96) 
- [ ] [servo360 - control system tuning](https://github.com/parallaxinc/Simple-Libraries/issues/95) 
- [ ] [servo360 - remove remove jitter from servo signal](https://github.com/parallaxinc/Simple-Libraries/issues/94) 
- [ ] [servo360 - increase number of servos supported](https://github.com/parallaxinc/Simple-Libraries/issues/93) 
- [ ] [servo360 - prevent binary overflow of 12-bit angle](https://github.com/parallaxinc/Simple-Libraries/issues/92) 
- [ ] []()
