### ISSUE TITLE
servo360/abdrive360 Simple Library Minimum Checklist

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/Simple-Libraries#139]
Minimum Requirements for blockly servers
- [x] ifdef guards
- [x] Mangle global variable names.
- [x] Update constant names
- [x] Reduce cog space

**Comment by AndyLindsay** [comment]
[#139 Update constant names](https://github.com/parallaxinc/Simple-Libraries/commit/e51c82a0ee884f1aa60d790f00a39b11a1dc7db6)
[#139 ifdef guards](https://github.com/parallaxinc/Simple-Libraries/commit/4d9b7ee81d204331c33ae8fe2841513ca39f24d9)
[#139 Update constant names (that were missed on first round)](https://github.com/parallaxinc/Simple-Libraries/commit/080483ed8e51f57ec8b9531eed9e89ede841d565)
[#139 Mangle global variable names, part 1](https://github.com/parallaxinc/Simple-Libraries/commit/97ccb94bdb20d31c7dabdfc5292d4c24c420bb07)
[servo360/abdrive360 Simple Library Minimum Checklist #139](https://github.com/parallaxinc/Simple-Libraries/commit/ca2145265a5131c4d58abc6c978898f6955d5839)
